### ISSUE TITLE
isucon過去問をプロファイラ使いながらチームで解く

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#1]

**Comment by IkezoeMakoto** [comment]
zoeチーム @zoe  @Sorarinu @02 @buch
pinkumohikanチーム @pinkumohikan @okashoi @masami @ういろう

チーム対抗戦やっていき！！

**Comment by IkezoeMakoto** [comment]
isucon9 に向けて練習しよう

http://isucon.net/archives/53024809.html

**Comment by IkezoeMakoto** [comment]
なぜか無限LTのissueが紐づいてる

**Comment by pinkumohikan** [comment]
何か適当にやった気がする
