### ISSUE TITLE
2chまとめアンテナ作る

### ISSUE THREAD

**Issue by pinkumohikan** [oystersjp/neta-note#11]
# 概要
* @yopidax と2chまとめ記事収集 & 配信プラットフォームを作ったので、コスト低くアンテナサイトが作れるようになった
* みんなでアンテナサイト作ってトラフィック流しあえば、お小遣い稼ぎが出来るのではないか

**Comment by pinkumohikan** [comment]
入社直後に作っていたアンテナサイト
https://niwatori-antenna.com/

**Comment by IkezoeMakoto** [comment]
トラフィックを流し合えば、流入が増えお小遣いが稼ぎやすい。

つまり牛丼食べ放題

**Comment by pinkumohikan** [comment]
https://github.com/oystersjp/octopus-client-golang

**Comment by pinkumohikan** [comment]
アンテナサイトの設計
----
1. テーマを決める
1. キーワードを洗い出す

**Comment by IkezoeMakoto** [comment]
test

**Comment by pinkumohikan** [comment]
redashに投げるクエリ
```
SELECT *
FROM article
WHERE title LIKE '%転職%'
  OR summary LIKE '%転職%'
ORDER BY created_at DESC;
```

**Comment by IkezoeMakoto** [comment]
hoge

**Comment by pinkumohikan** [comment]
あとは個人で進めましょう
https://oystersjp.slack.com/messages/CDJ3MMC0G
