### ISSUE TITLE
3ヶ月間振り返り会

### ISSUE THREAD

**Issue by okashoi** [oystersjp/neta-note#121]
そろそろね

see also: #26

**Comment by pinkumohikan** [comment]
やりませう

**Comment by pinkumohikan** [comment]
今回のTry

* 共有のテンプレっぽいもの作っとく (例えばこういう項目、ぐらいの位置づけ)
* 共有に時間制限設ける

https://github.com/oystersjp/neta-note/issues/26#issuecomment-515752029

**Comment by pinkumohikan** [comment]
調整さん作った:
https://chouseisan.com/s?h=b70735b204ff4c5782f6ac75351ff5f0

**Comment by pinkumohikan** [comment]
11/9 (Sat) でfix

**Comment by pinkumohikan** [comment]
参加予定者: ぴんくもひかん、おかしょい、02、アキバ、ういろう、ヒロ高、Yu

**Comment by okashoi** [comment]
11月9日（土）11:00 から、ウィルゲートの Room3 おさえました〜

**Comment by ShuzoN** [comment]
にょ、俺も行きたい

**Comment by IkezoeMakoto** [comment]
暇だったら行く

**Comment by Yu0614** [comment]
### 振り返り テンプレ 

https://oystersjp.slack.com/archives/C7L6CMLAJ/p1573271939019100  

 @pinkumohikan さんありがとうございます。

**Comment by okashoi** [comment]
ふりかえった

**Comment by okashoi** [comment]
ブログも書いた

https://blog.okashoi.net/entry/2019/11/10/110000
