### ISSUE TITLE
「ボトムアップドメイン駆動開発」の資料を読む会

### ISSUE THREAD

**Issue by okashoi** [oystersjp/neta-note#15]
## 背景

https://oystersjp.slack.com/archives/C4PLCR7D2/p1540342291000100

> okashoi [09:51]
> 昨日参加した勉強会、めちゃくちゃ良かった（スライド枚数めっちゃ多い）
>
> https://togetter.com/li/1280211

## やること

「ボトムアップドメイン駆動開発」の資料を読みながら、勉強会に参加していた岡田が解説をする

内容について議論する

## 資料

* https://www.slideshare.net/MasanobuNaruse/bottomup-ddd-1
* https://www.slideshare.net/MasanobuNaruse/bottomup-ddd-2

（スライド計約400枚）

**Comment by pinkumohikan** [comment]
良い学びであった

@okashoi thanks!
