### ISSUE TITLE
クラス・変数名をアンケートによって決めるサービス作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#16]
## 発端
https://oystersjp.slack.com/archives/CDN1WAH0F/p1541564712007800

## 案
* クラス・変数名の選択肢と簡単な背景だけ投稿し、アンケートによる投票で決める
* twitterのツイートを蓄積しておいて検索できる

既存のサービスがあれば、closeします

**Comment by okashoi** [comment]
UI はこのサイトに近い感じになるイメージかな？（このサイト、結果の信憑性は著しく低いけどw）

http://yomikata.org/

**Comment by okashoi** [comment]
twitter 投票だと

* 第三者が新しい選択肢を追加できない
* 選択肢が4つまで

という制約がある

**Comment by cocoeyes02** [comment]
owl で実装中なので issue 自体は一回閉じます
