### ISSUE TITLE
確定申告のやり方を学ぶ会

### ISSUE THREAD

**Issue by okashoi** [oystersjp/neta-note#21]
今年はじめて副業やったので、確定申告のやり方を学びたい

**Comment by pinkumohikan** [comment]
機運が高まってきた
https://biz-owner.net/kakutei/kikanv

**Comment by pinkumohikan** [comment]
去年は確かここで資料作って、書類添付して郵送で送った記憶
https://www.keisan.nta.go.jp/kyoutu/ky/sm/top#bsctrl

**Comment by pinkumohikan** [comment]
投資やってる人向け

株で損失が出たら絶対確定申告！損益通算をして繰越控除をしよう
https://orekabu.jp/loss-on-the-stock-market/

**Comment by pinkumohikan** [comment]
収支の数字を証明する書類は5年間残しておこう

https://twitter.com/gahyu55/status/1094129143426342912

![image](https://user-images.githubusercontent.com/7835241/52547748-11d2f000-2e0d-11e9-8191-830c85a7741b.png)

**Comment by pinkumohikan** [comment]
おつかれさまでした
