### ISSUE TITLE
第2回 無限LT会

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#22]
人数も増えてきたので、親睦を深めるためにもLTの敷居を下げるためにもやりたい

**Comment by IkezoeMakoto** [comment]
いつやりますか！？

**Comment by cocoeyes02** [comment]
今月(3月)中にはやりたいっすね！！

**Comment by cocoeyes02** [comment]
日程調整中
https://oystersjp.slack.com/archives/C7L6CMLAJ/p1551403077005800

**Comment by cocoeyes02** [comment]
いい会だった
