### ISSUE TITLE
公開版無限 LT （第3回無限 LT 会）

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#24]
## 何故やりたいか
* 無限 LT 会自体かなりいい企画なので、oysters 外以外の人も含めて定期開催しても良いんじゃないかと思った
* oysters メンバーを定期的に探せそう

## 決まっていないこと・わかっていないこと例
* 募集方法（connpass 等で募集する？）
* ルール
* そもそもやりたい人がいるか

**Comment by okashoi** [comment]
（前回までのあらすじ）PHPKaigi 2019 のアンファンレンスにて、ついに「無限 LT」の存在が世に公開されてしまったのである！

https://twitter.com/ShuzoN__/status/1112209300582076416

https://twitter.com/nyamucoro/status/1112210921982615552

**Comment by cocoeyes02** [comment]
【朗報】ついに無限LT導入企業現る

https://www.infiniteloop.co.jp/blog/2019/04/phperkaigi-2019/


この勢いに乗って「ワシらが育てた」感を出していくとか

**Comment by klack710** [comment]
[Oysters] 無限LT会 #1
のconnpassイベントを立てる。

一旦私が責任持って進めるよ！

**Comment by cocoeyes02** [comment]
わいわい

**Comment by klack710** [comment]
一旦oystersのグループ作成 done
https://oysters.connpass.com/

**Comment by IkezoeMakoto** [comment]
開催までにやるべきことはなんだろう？

**Comment by klack710** [comment]
1. 開場確保 done
2. イベントページ (現在メンバーにreviewしてもらっているところ)
3. 募集公開
4. 広報！！！(ゴールは5人参加表明出るところ)
5. (もし5人超えたら)枠増加

**Comment by IkezoeMakoto** [comment]
やるべきことごとにコメントして、そこからissueを立てて、issue単位で進捗を残そう

**Comment by cocoeyes02** [comment]
あるいは別 repository にするとか

**Comment by IkezoeMakoto** [comment]
別レポジトリは定期開催等決まってからでいい感

**Comment by klack710** [comment]
一旦イベントページのissue作るね。
ここのスレッドは、全体の進捗管理のために残そう。

**Comment by IkezoeMakoto** [comment]
日程の確定

**Comment by IkezoeMakoto** [comment]
会場の確定

**Comment by IkezoeMakoto** [comment]
運営メンバー誰がやるのか

**Comment by IkezoeMakoto** [comment]
当日の運営の流れ

**Comment by IkezoeMakoto** [comment]
振り返り

**Comment by klack710** [comment]
今後のスケジュール

1. 日程の確定 #30
2. 会場の確定 #31
3. 公開版無限LTのconnpassイベント作成(+レビュー) #29
4. 運営メンバー誰がやるのか #32
5. 当日の運営の流れ #33
6. 振り返り #34

**Comment by IkezoeMakoto** [comment]
commentからissue切ってるからrefいらんで

**Comment by IkezoeMakoto** [comment]
どちらかというとかんばんが欲しい

**Comment by IkezoeMakoto** [comment]
イベント前日通知

**Comment by IkezoeMakoto** [comment]
連絡先の決定

**Comment by IkezoeMakoto** [comment]
名刺作りたい

**Comment by IkezoeMakoto** [comment]
まだなんかヌケモレがある感覚があるけど、なんだろ、わからん

**Comment by IkezoeMakoto** [comment]
事前説明の準備（会場案内、当日の流れを説明）

**Comment by IkezoeMakoto** [comment]
受付担当の決定

**Comment by IkezoeMakoto** [comment]
会場案内担当の決定

**Comment by IkezoeMakoto** [comment]
タイムキーパーいる？

**Comment by IkezoeMakoto** [comment]
会場提供LTやる？ 

主に @okashoi 向け

**Comment by okashoi** [comment]
タイムキーパーは LT の時間測定ならいるかな

学会タイマーを使うとして、それ用に PC が 1 台いる（LT する人の PC 使うなら、複数台交代で）

**Comment by okashoi** [comment]
会場提供からの宣伝枠はほしい。やるつもり。

**Comment by okashoi** [comment]
あと司会進行役が別途必要だと思う。

**Comment by IkezoeMakoto** [comment]
> あと司会進行役が別途必要だと思う。

わかる

**Comment by cocoeyes02** [comment]
あ、アンケートの内容考えないといけないっすね

あと強いていうならば、クロージングとかどうします？
次回の日程の話とか、無限LT終了後の懇親会（用意するならば）とか話せそうですが

**Comment by IkezoeMakoto** [comment]
クロージング確かにな。司会進行の人に一旦聞いてみる？ @klack710

**Comment by klack710** [comment]
クロージング、その場で無限LTの要領で作るつもりだった(*ﾉω・*)ﾃﾍ

次回日程は話してもいいけど、
そもそも、人が集まるかすら怪しかったので、反省会次第で日付が変わりそうな予感がしている。
その場で話す効果があまり見えてない。

懇親会は実は私は計画する予定なかったり。次の日月曜日だから、私あまり長居出来ないもので・・・！

**Comment by cocoeyes02** [comment]
> クロージング、その場で無限LTの要領で作るつもりだった

慣れてないとクロージング即興でやるのは難しい（と思う）ので、なるべく準備した方が良いかと！

> そもそも、人が集まるかすら怪しかったので、反省会次第で日付が変わりそうな予感がしている。

:wakaru:

> 懇親会は実は最初私は計画する予定なかった。次の日月曜日だから、私あまり長居出来ないもので・・・！

懇親会をやる目的は、リレーション作りが主な目的になるはずです！
その辺が今回は不要と判断するならば、特に計画しなくても良いかもです！
皆さんはどう思いますか？

**Comment by IkezoeMakoto** [comment]
懇親会、長居できないって言っても終わるの18時なんでみんなでご飯食べて解散くらいなら行けない？？
個人的には無限LTの時間だけだと相互コミュニケーションは取れないので、ご飯食べながら自由に話す時間とかあると嬉しいなと思ってる。

**Comment by IkezoeMakoto** [comment]
イベント開催1週間前切りました！残りタスクもまだあるので、頑張っていいイベントにしましょう！

よろしくおねがいします！！

**Comment by IkezoeMakoto** [comment]
@klack710 懇親会やるやらないどうしますか？推進者なのでもう決めちゃってくださいな。

https://github.com/oystersjp/neta-note/issues/24#issuecomment-488236263

**Comment by klack710** [comment]
では、公式な懇親会はなしで！

よくあるイベント後に任意で『みんなで飯行きません？』みたいに言うのは止めない
って感じでどうでしょう？

ってことで、一旦店の予約とかはしない方向で考えています！

**Comment by masaki-obata** [comment]
ちなみに、懇親会やるなら、片付けが終わるまで参加者は待機してもらう感じ？

**Comment by masaki-obata** [comment]
@cocoeyes02 @IkezoeMakoto 
タスク多くて申し訳ないけど、懇親会やるのであれば、二人のどちらかボール持ってほしいー

**Comment by klack710** [comment]
ちなみに、懇親会やるなら、片付けが終わるまで参加者は待機してもらう感じ？  
片付け私がやるにしても、WGの人ひとりはのこってほしい。

私とWG１人以外の人で、先に懇親会用に会場確保して誘導するのはあり

@cocoeyes02 @IkezoeMakoto  
タスク多くて申し訳ないけど、懇親会やるのであれば、二人のどちらかボール持ってほしいー

**Comment by cocoeyes02** [comment]
特に何もなければ僕がやりましょうかー？（今回はやらないと思いますが）

**Comment by klack710** [comment]
もし今回懇親会しないなら、振り返りを当日にやりたいなーっていう個人的なお気持ち

**Comment by klack710** [comment]
そこも含めて一旦02がissue立ててもらってもよい？

**Comment by cocoeyes02** [comment]
> もし今回懇親会しないなら、振り返りを当日にやりたいなーっていう個人的なお気持ち

『みんなで飯行きません？』みたいに非公式でやる時、運営一切参加しない感じになりますが大丈夫ですかね

**Comment by cocoeyes02** [comment]
一旦懇親会についてで issue 立てます！

**Comment by okashoi** [comment]
どっちみち片付けは最後まで WG 社員必須ね（施錠とかもあるので）

会場設営と片付けのフローは書き出しておきたいな

**Comment by IkezoeMakoto** [comment]
一旦完！あとは振り返りがあるけど、実施自体は終わったので閉じます
