### ISSUE TITLE
過去3ヶ月間のやったこと、成長したこと、懺悔を振り返る会

### ISSUE THREAD

**Issue by pokuty** [oystersjp/neta-note#26]
やること
----
* 過去3ヶ月間のセルフKPTをやる
* 話せる範囲で共有する
* (必要に応じて) Wantedlyや職歴書を更新する

なぜやるか
----
https://oystersjp.slack.com/archives/C7L6CMLAJ/p1554008138038200
```
pinkumohikan [13:53]
www
3ヶ月に1回、3ヶ月間の実績や成長をまとめる会をやりたいなと思った
最後に職歴書書いたの1年前で、過去1年間何してたっけってなってるからｗ
```

**Comment by pokuty** [comment]
アカウントまちがえたわｗ

**Comment by pinkumohikan** [comment]
ここで調整していきます
https://chouseisan.com/s?h=92812a86bd9a41be847e55f6a39751fe

**Comment by ShuzoN** [comment]
おっす

**Comment by ShuzoN** [comment]
アルデバランとった

**Comment by pinkumohikan** [comment]
7/27 (土) 13:30 - 16:00 at VGで確定

**Comment by pinkumohikan** [comment]
無事、昨日開催した

* 次回: 10月
* 次のTry
    * 事前に共有のテンプレっぽいもの作っとく
    * 共有に時間制限設ける

**Comment by pinkumohikan** [comment]
ブログを書いた:

> 【ムキムキ会】直近3ヶ月間の人生を振り返る会をやった

https://blog.pinkumohikan.com/entry/mukimukikai-1st
