### ISSUE TITLE
Oysters の紹介サイトを作る

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#27]
shuzon [10:20]
あ、Oystersのサイト作りますか？

shuzon [11:06]
https://themes.gohugo.io/hugo-orbit-theme/
https://themes.gohugo.io/forty/

02 [11:10]
:tukurou:

**Comment by cocoeyes02** [comment]
最低限だと

・何をする団体なのか
・参加メンバー一覧

は入れたいですね…他に何かありますか？

**Comment by klack710** [comment]
活動例・その風景

活動実績(connpassつくってしまうとか、旧サイトのスクショとか)
ブログリンク(参加メンバーに書くのも○)

**Comment by pokuty** [comment]
* 活動実績、予定 (の知り方)
* 活動に興味があります！
とか

**Comment by klack710** [comment]
メンバー集めるなら、導線とか何かしらあってもいいかも

**Comment by klack710** [comment]
Oysters web-site 開発のキックオフと内容詰め

4/28開催
主導は @cocoeyes02 が今やってくれてる

**Comment by cocoeyes02** [comment]
続きは[こっちの Repository で](https://github.com/oystersjp/oystersjp.github.io)

**Comment by IkezoeMakoto** [comment]
移行したのでクローズ
