### ISSUE TITLE
GW にボトゲる会

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#28]
発端はこの辺り参照
https://oystersjp.slack.com/archives/CDN1WAH0F/p1555399157015200

VG がオフィス使えないかも？ということなので、会場は WG になるかも

**Comment by IkezoeMakoto** [comment]
いいぞ

**Comment by cocoeyes02** [comment]
https://oystersjp.slack.com/archives/C7L6CMLAJ/p1555911271008700

**Comment by cocoeyes02** [comment]
あと、WG にあるボードゲームもたぶん遊べると思います！（何があったかは忘れた）

**Comment by IkezoeMakoto** [comment]
調整さんのリンクはらないと意味ないんじゃ（ログはいつか消える

https://chouseisan.com/s?h=56b23d1b8fb8452c96704fb6e3bb6c89

**Comment by cocoeyes02** [comment]
残念ながら延期です。。。（GW でという内容だったので一回クローズします）
