### ISSUE TITLE
公開版無限LTのconnpassイベント作成(+レビュー)

### ISSUE THREAD

**Issue by klack710** [oystersjp/neta-note#29]
ツリー元 #24 

このissueは公開してるけど、
管理権限渡してる人だけ見れる！

一旦ういろうが仮作成したので、レビューや修正よろしく！

https://oysters.connpass.com/event/129365/preview/

**Comment by klack710** [comment]
日付と場所は、slack内で相談してfix済み
人数に関しても、既に相談済み。未fixではあるので、追加意見○

https://oystersjp.slack.com/archives/C7L6CMLAJ/p1556247505009200?thread_ts=1556159204.053100&cid=C7L6CMLAJ

■未fix
1. 説明文
2. キャッチ画像

**Comment by IkezoeMakoto** [comment]
できればPRでレビューしたい

**Comment by IkezoeMakoto** [comment]
>対象の人
>LT初心者～LT上級者まで
>若手エンジニアである必要もないです！
どんな人にきて欲しいか、不向きな人はどんな人か。がわかるような文章にしたい

例えば、

```
▼こんな人にきて欲しい！
・無限LTを通してLTのトークスキルを向上させたい人
・自分の持っている面白いトークを披露したい人
・今ネタはないけど話を聴きながらでもLTネタを作ってみんなでわいわいしてみたい人

▼不向きな人
・ネタはないがみんなの話を聞いてみたい人
```

**Comment by IkezoeMakoto** [comment]
提供情報に、用意している接続端子や、wifi有無、電源有無もあると良さそう。

接続端子は確認しないとわからない

**Comment by klack710** [comment]
接続端子はごめん、私は流石にわからない！！！
GW中に確認は可能？？

**Comment by IkezoeMakoto** [comment]
多分確認できると思う〜
まぁ最悪当日までにわかればいいので！

**Comment by klack710** [comment]
> こんな人に来てほしい等

良さそうだけど、そのままだとちょっと惜しい感してる。
一般的な内容の会ではないので『自分は対象になりえるのか？』がひと目で感じられるようにしたい。
なので混ぜてみた


■大枠  
LT初心者～LT上級者まで

#### こんな人は楽しめそう！

* 無限LTを通してLTのトークスキルを向上させたい人
* 自分の持っている面白いトークを披露したい人
* 今ネタはないけど話を聴きながらでもLTネタを作ってみんなでわいわいしてみたい人

#### 不向きな人

* ネタはないがみんなの話を聞いてみたい人

**Comment by klack710** [comment]
> 接続端子

OK!じゃあ、募集ページの公開はしよう。で、端子を調べるに関しては、issue立てるので、WGの人で相談して対応してほしい！！！

**Comment by klack710** [comment]
あ、レビューしてみて、特に意見ない人も、何かしらスタンプとかでリアクションくだしあ

**Comment by IkezoeMakoto** [comment]
リアクションというかPR出して欲しい

**Comment by IkezoeMakoto** [comment]
コンパス公開時に告知をしたいね、ツイッターとかで。

**Comment by klack710** [comment]
レビューの日付決めちゃおうか。
一旦4/28を募集公開日として、
レビューは明日の昼までで。

**Comment by BBCapMegane** [comment]
作成ありがとうございます！
プレビュー画像は、LTとういうより**無限**を強調したものが良いかと思います！
(LT会は沢山あるので、無限であることを押していきたいという個人的なおもいです)

### 案1
無限の記号
![inf](https://user-images.githubusercontent.com/28012205/56847233-70d7d980-6913-11e9-876f-9791b6a3947c.png)


### 案2
無限の漢字
![mugen](https://user-images.githubusercontent.com/28012205/56847244-995fd380-6913-11e9-8819-7ae828a11a9c.jpg)

### 案3
無限ループ
<img width="374" alt="tmp2_html" src="https://user-images.githubusercontent.com/28012205/56847328-4d615e80-6914-11e9-9b0b-e61e38f7818a.png">

**Comment by okashoi** [comment]
会場についての案内が必要。
こんな感じかな

```
休日についてビルのエントランスは閉まっています。
到着したら<連絡先※>までお知らせください。
運営の者が向かいますので、無限 LT の参加者であること確認のうえ、会場まで案内いたします。
```

※運営側の誰かに twitter 等で連絡してもらい、WG社員が向かう

**Comment by okashoi** [comment]
アイキャッチ画像は @BBCapMegane の案2に近い感じで「無限LT」とでっかく書いた文字だけでいいかもｗ

**Comment by okashoi** [comment]
あとはよさそう！

**Comment by cocoeyes02** [comment]
そういえば今回の無限LTって、どんな流れでやるかって決まってないんでしたっけ？

決まってるならざっくりと書いても良いかもです！（くじ引きで順番を決めて、休憩挟みつつずっとLTするとか）

**Comment by klack710** [comment]
連絡先、twitter限定だけど大丈夫かな。

あるいは私の個人メール晒す？

**Comment by klack710** [comment]
みんなレビューありがと～！

一旦これでOKなら公開します！最終レビューお願いします！
もし、画像のいい案があれば、作成して突っ込んでくれると嬉しい！

https://oysters.connpass.com/event/129365/preview/

**Comment by IkezoeMakoto** [comment]
何回も言ったんですが、、コンパスのページに書いてる内容をPRにしてほしいのです。

意図としてはレビューする側がコンパスの内容見てFBするときに毎回コピーして引用して指摘して、ってのがすごい面倒だからです。

PRであれば、承認もできるのでPRのほうがいいと思ってます。

ということで現時点で私はあまり内容についてレビューできていないです。

**Comment by klack710** [comment]
> コンパスのページに書いてる内容をPRにしてほしいのです。

ごめんなさい！！！今意味がわかりました！直ちに作ります！

**Comment by klack710** [comment]
@IkezoeMakoto 

意図がうまく掴めてないけど、こういうことで合ってる？？？

https://github.com/oystersjp/neta-note/pull/42

**Comment by klack710** [comment]
公開しました！！！
がんばろー！！！
