### ISSUE TITLE
運営メンバー誰がやるのか

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#32]
運営メンバー誰がやるのか

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487077992_

**Comment by klack710** [comment]
メインの運営は私でいいんだけど、
今回会場が私じゃどうしようもなかったので、
会場の解錠とか、機器の準備とかで、どうしてもWGの人を1~2人は運営をしてほしい。

もし良ければ、指名しちゃうけど @okashoi @cocoeyes02 の二人に手伝ってほしい！

2名な理由は、リスク低減。最悪私がいなくても代わりを用意する方法はあるけど、  
WGの人がいないと中止が確定してしまうので！

**Comment by okashoi** [comment]
もちろんやるでー！

**Comment by IkezoeMakoto** [comment]
わいはメインじゃないけど、バックアップ要員として入っとくで

**Comment by IkezoeMakoto** [comment]
当日スタッフ枠とかあってもいいかもね

**Comment by klack710** [comment]
みんなありがとー！

ういろう、おかしょい、02で運営。

ぞえさんがバックアップ要員でやろうと思います！  
当日スタッフ枠に関しては、一旦初回なので、不確定要素増やしすぎないために、次回にまわしたいお気持ち！

**Comment by klack710** [comment]
@IkezoeMakoto 

当日スタッフ枠は、一旦初回なのでなしにしたいと思いますー！
特に意見がなければ、このカードクローズします！
