### ISSUE TITLE
当日の運営の流れ

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#33]
当日の運営の流れ

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487078137_

**Comment by IkezoeMakoto** [comment]
会場提供LTやりたいね

**Comment by IkezoeMakoto** [comment]
懇親会的なのやる？

**Comment by IkezoeMakoto** [comment]
当日の事前打ち合わせは軽くやっておきたいね

**Comment by IkezoeMakoto** [comment]
12:00 会場
13:00 受付開始
17:00 解散
18:00 閉場

**Comment by IkezoeMakoto** [comment]
当日の流れを会場のみやすいところのWBに書いておきたい

**Comment by klack710** [comment]
> 当日の流れを会場のみやすいところのWBに書いておきたい
> wi-fiの接続情報とかも

これの作成は別カード作ろう！作っておくね！

**Comment by klack710** [comment]
仮スケジュール


12:30 - 13:00 開場・受付  
13:00 - 13:15 オープニング・説明・デジタルくじ引き   
13:15 - 14:00 自己紹介LT(各2~5分)  
14:00 - 17:00 無限LT  
17:00 - お片付け

**Comment by klack710** [comment]
@okashoi @cocoeyes02 

> 事前打ち合わせ
運営の事前打ち合わせをどっかでしたいー

■候補:

1. GWの平日に、ランチ
2. WGもくもく会帰りに飯食いながら
3. LT会前日に私の家で、BeatSaberしながら

**Comment by IkezoeMakoto** [comment]
> 12:00 開場
> 13:00 受付開始
> 17:00 解散
> 18:00 閉場

> 当日の事前打ち合わせは軽くやっておきたいね

当日12時に開場なので11時くらいに集まっておけばいいかな

**Comment by okashoi** [comment]
LT会開始が 13:00 なので、運営者 12:00 集合想定している。
会場のセッティングとかもろもろ考えても受付開始（12:30）から逆算しても 30 分くらいあれば良いかなーという。

（空調の稟議出すときに 12:00 からにしてある、というだけなので、その前に集まるのは問題なしではある）

**Comment by okashoi** [comment]
@klack710 

> ■候補:
> 
> 1. GWの平日に、ランチ
> 2. WGもくもく会帰りに飯食いながら
> 3. LT会前日に私の家で、BeatSaberしながら

私は 2 がよいです！

**Comment by okashoi** [comment]
ホワイトボードは使えるのあるか微妙だな、要確認。

**Comment by klack710** [comment]
@cocoeyes02 WGもくもく会来れそう？

**Comment by cocoeyes02** [comment]
WGもくもく会は大丈夫ですが、それ以降は別の予定が入ってるのでちょっと怪しいかもです…保留でお願いします！

**Comment by IkezoeMakoto** [comment]
> ■候補:
> 
> GWの平日に、ランチ
> WGもくもく会帰りに飯食いながら
> LT会前日に私の家で、BeatSaberしながら

これ今更で本当に申し訳ないのだが、今週のもくもく会の日私参加できないんだった、、すまねぇ

**Comment by masaki-obata** [comment]
@IkezoeMakoto @okashoi @cocoeyes02 
これ、金曜日の私の家でBeatSaberしながらに変更したいです！！！！

**Comment by okashoi** [comment]
一部こっちとかぶったかも

https://github.com/oystersjp/neta-note/issues/52#issuecomment-490858098

**Comment by klack710** [comment]
■オープニングスライド
https://docs.google.com/presentation/d/1wZPyDZKVo_pOQuQMxcaB_Y00VIdZUh511eytKz3R5PM/edit?usp=sharing

(会場の諸注意は、#52でおかしょいが作ってくれますー！)

**Comment by IkezoeMakoto** [comment]
http://www.daiichi-g.co.jp/osusume/forfun/02_amida/02.html

**Comment by IkezoeMakoto** [comment]
> ■オープニングスライド
> https://docs.google.com/presentation/d/1wZPyDZKVo_pOQuQMxcaB_Y00VIdZUh511eytKz3R5PM/edit?usp=sharing
> 
> (会場の諸注意は、#52でおかしょいが作ってくれますー！)
> 確認して、良さそうであればスタンプお願いしますー！

これ確認しました。

>他の人の話を聞きながらLT作ったら、無限にLTできるよね

ここだけちょっと話すときに注意したほうがいいかもしれないと思いました。

**話を聞かないで次のLTネタをただ作ってもいい** と伝わると嫌だなと思っていて、、、

（当たり前だけど）あくまでLT話してくれてる人に敬意を評しつつ、話し方や話してる内容から刺激（インスピレーション）や学びをもらいつつ、それをそのまますぐ活かす、みたいなイメージ。

なので、話を聞かないで次のLTネタをただ作る、のとは違うよ。というニュアンスを持って説明したい。
（良い発表だったら拍手や歓声などでリアクションしてください。とか）

**Comment by klack710** [comment]
1. 無限LTとは？→LT中にLT資料作れば無限にLTできる
2. よく陥りがちな注意点
3. LTを聞こう。良い発表に良いリアクション。LTすることだけを目的にしない
4. LT聞く→感動を覚える→真似したい……→真似できないが普段
5. ここでは、LT聞いて、すぐに真似して、すぐにLT出来る。
6. 聞くありきでLT会に臨もう。だから、LT資料間に合わなければスキップも当然あり！
7. でも0回はなしで！みんな覚えてますか？みなさんLT枠ですよ！

**Comment by IkezoeMakoto** [comment]
した
