### ISSUE TITLE
振り返り

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#34]
振り返り

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487078354_

**Comment by IkezoeMakoto** [comment]
日程と場所を抑えてちゃんと振り返りをしたい

**Comment by IkezoeMakoto** [comment]
参加者も決めないとな。

できれば日程は実施した翌週の土日がいいかなと思いますがどうですかね？

**Comment by IkezoeMakoto** [comment]
@klack710 @okashoi どうですか？

**Comment by klack710** [comment]
OK!
ちなみに、翌々週だと、出張のために東京にいないです(´；ω；｀)

**Comment by okashoi** [comment]
振り返りはやりましょう、日程は翌週の土日でもいいけど

当日のほうが記憶が薄れてなくて良いかな、というおきもち

**Comment by masaki-obata** [comment]
当日やるなら、懇親会がなくなる？
あるいは、懇親会兼振り返り・・・？

**Comment by IkezoeMakoto** [comment]
当日でも自分はありっすよ〜

**Comment by okashoi** [comment]
あー懇親会があったか
参加する人の属性が異なるので兼ねるのはできないと思う。

懇親会やるなら次週に持っていったほうがいい、という意見です（懇親会のほうが優先度高そう）

**Comment by klack710** [comment]
反省

前日に詰めてるのはちょっと良くなかったね
きっちり計画管理してるのは良い
運営にコストかかるのはもったいない
回数重ねたら効率化していきそう

**Comment by klack710** [comment]
キックオフやろう

**Comment by klack710** [comment]
温度感の差

そんなに頑張らなくてもイベント開催はできるよ
→キックオフしてたから認識統一できたかもね

**Comment by IkezoeMakoto** [comment]
質問有り無しを事前に考える

**Comment by IkezoeMakoto** [comment]
oystersのグーグルドライブに振り返り用のスプレッドシート用意しておいたのでこちらに記載しておいていただけると助かります〜
（多分一週間後だと忘れるので

**Comment by IkezoeMakoto** [comment]
そういえば、18日（土）予定入ってるの忘れてたのでできれば19日（日）にやりたいのですが、どうですかね？

**Comment by cocoeyes02** [comment]
OK です！会場はどこにしますかー？

**Comment by ShuzoN** [comment]
18, 19日奇跡的に空いてるので自分つきあえますよ

会場はvgでいいのでは？

**Comment by klack710** [comment]
■候補
1. 通話(オンライン)
2. 私の家(beatsaberあり)
3. 私の家(beatsaberなし)
4. てきとーに店
5. WGで会議室
6. VGで会議室

**Comment by okashoi** [comment]
VGの新オシャオフィスに行ってみたい

**Comment by IkezoeMakoto** [comment]
>VGの新オシャオフィスに行ってみたい

わかる

**Comment by ShuzoN** [comment]
いいぞっ
ちなみに写真よりもめちゃくそオシャレ

**Comment by BBCapMegane** [comment]
自分も振り返り参加したです！
(決してVGに行きたいからだけではない)

**Comment by klack710** [comment]
では一旦VG確定で！
振り返り参加は歓迎ですよ！

**Comment by klack710** [comment]
振り返り参加予定者
@klack710 
@okashoi 
@cocoeyes02 
@IkezoeMakoto 
@ShuzoN 
@BBCapMegane 

他にいたら教えて下しあ

**Comment by klack710** [comment]
@ShuzoN 
一旦、会議室取れなかったかわかった時点で教えてください。

@全員
会議室用意出来なかった場合の別なパターンのアンケート取りたいですー

1. 通話(オンライン)
2. 私の家(beatsaberあり)
3. 私の家(beatsaberなし・たこ焼きでも作りながら話す？)
4. てきとーに店

**Comment by okashoi** [comment]
> 私の家

この人数入れそう？ 🤔

**Comment by klack710** [comment]
beatsaberしなければ大丈夫／(^o^)＼
まあ狭いとは思うけどね！

**Comment by okashoi** [comment]
4. に近いかもだけどコワーキングスペース的なのとか（今、具体的な場所を知っているわけじゃない）

**Comment by ShuzoN** [comment]
ん？会議室は取れてるよ。ビルに入るためのQRコードが発行できるかわからないけどこの辺はまぁなんとかなります

**Comment by klack710** [comment]
なるほど？
ではとりあえず当日VG近く行けば入れるのは間違いない感じ？

**Comment by ShuzoN** [comment]
今申請フローを爆速で進めてもらってるー
多分間に合うと思う(社長で止まってた)

**Comment by ShuzoN** [comment]
会社名とうとうめちゃくちゃだけどとりあえず来客予約した

![image](https://user-images.githubusercontent.com/5877377/57920989-486e4a00-78d7-11e9-8784-17f7e544f664.png)

**Comment by ShuzoN** [comment]
みなさんにDMでQR送ったのでチェックしてね
これをゲートにかざすと入れます。

**Comment by pokuty** [comment]
多分きっと俺も参加する

**Comment by cocoeyes02** [comment]
振り替えたのだった
https://scrapbox.io/oystersjp/%E7%84%A1%E9%99%90_LT_KPT
