### ISSUE TITLE
かんばん整備

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#35]
どちらかというとかんばんが欲しい

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487080451_

**Comment by klack710** [comment]
んじゃ私で用意してみるー！

**Comment by klack710** [comment]
あ、既に作ってくれてた・・・ｗあざますー

**Comment by IkezoeMakoto** [comment]
お,すまん、じゃここからたのんだ

https://github.com/oystersjp/neta-note/projects/1

**Comment by klack710** [comment]
@IkezoeMakoto 
おｋ
じゃあレビューまかせた！

**Comment by klack710** [comment]
@IkezoeMakoto 
イメージこんな感じで合ってる？

**Comment by IkezoeMakoto** [comment]
よさそう

#24 もかんばんにいれたい

**Comment by klack710** [comment]
レビューさんく！追加した！

**Comment by IkezoeMakoto** [comment]
良さそう。一旦クローズ
