### ISSUE TITLE
イベント前日通知

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#38]
イベント前日通知

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487124723_

**Comment by IkezoeMakoto** [comment]
予め文言考えておいて前日送るだけにしておきたい。

（以前違うコミュニティで誤った情報を送ってた過去があるので

**Comment by IkezoeMakoto** [comment]
これは他にやりたい人が誰もいなければ私が用意しますか

**Comment by IkezoeMakoto** [comment]
前日通知で伝えたいことはこんな感じかな？他にもあれば教えてください。

* 受付時間を含めた会の時間割り
* 会場の場所
* 受付に必要なもの

**Comment by cocoeyes02** [comment]
必要かどうかは置いといて、思いついたのだと以下ですかね

* 会場の入り方
* 当日遅れてくる場合の注意事項

**Comment by IkezoeMakoto** [comment]
会場の入り方ね、確かに

遅れてくる人の注意事項はPR作ったときに入れた！

**Comment by IkezoeMakoto** [comment]
前日になったので通知しますー

**Comment by IkezoeMakoto** [comment]
送った。

↑送信前にチェックしたら修正箇所合ったので反映用のPR出しているのでこちらマージしたらクローズ予定

**Comment by klack710** [comment]
良さそうなのでapproveしたー

**Comment by IkezoeMakoto** [comment]
マージしたのでくろーず
