### ISSUE TITLE
連絡先の決定

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#39]
連絡先の決定

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487124823_

**Comment by IkezoeMakoto** [comment]
当日遅れるとかそういうのの連絡先を決めておいてコンパスなどに載せておく

**Comment by klack710** [comment]
一旦以下を記載してるけど、何か意見あったらほしい！(現状Twitterしか連絡方法なし)
```
到着したら、twitterの以下にリプライ  
https://twitter.com/nyamucoro  

あるいはtwitterのハッシュタグ  
 #endless_lt  
```

**Comment by klack710** [comment]
ちなみに、Vue meetupとかは、Twitterのハッシュタグだけが当日の連絡先だったみたい。

今回入場に連絡必須とはいえ、一応ハッシュタグだけで当日の連絡先とするのは可能かも。(難しかったら、次回の反省に活かす)

**Comment by IkezoeMakoto** [comment]
代替案があるわけじゃないからあれ炊けど、ハッシュタグだと拾い漏れとかありそうであれだな〜とは思ってるけど、まぁ今回人数も少ないし、一旦いいかな〜？という気持ち

**Comment by klack710** [comment]
一旦連絡先はこれで！

もし今後問題あったら、issueのreopenをお願いします！
