### ISSUE TITLE
今後のキャリアを考えたり、履歴書・職歴書を書いたりする

### ISSUE THREAD

**Issue by pinkumohikan** [oystersjp/neta-note#4]
備えあれば憂い無し
「やべえ、書ける実績ねーわ」で業務に腰が入ることもあるしね

**Comment by pinkumohikan** [comment]
こちらにレジュメを用意しました
https://oystersjp.slack.com/archives/C2ZHPJVML/p1539491913000100

**Comment by klack710** [comment]
Done!
