### ISSUE TITLE
名札作りたい

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#40]
名札作りたい
作りたくない？

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487125393_

**Comment by IkezoeMakoto** [comment]
こういうのがあるらしい

https://www.askul.co.jp/p/662150/?sc_e=cp_p_as_go_pl_c&utm_source=go&utm_medium=PLA&utm_campaign=PLA_All&gclid=EAIaIQobChMItp_l9dDQ4AIVwrWWCh1HPggBEAQYASABEgIxPvD_BwE

**Comment by BBCapMegane** [comment]
いいね！
ただ以下も考えほうがよいかも
- お金(一人で負担するのは簡単だけど、よくはないよね)
- 渡したケースは回収する？(回収したら再利用できる)
- 名刺が必要なら事前告知が必要なのでは？
- 名刺ない人に配慮する？(ない場合は紙に書いてもらう？)

**Comment by klack710** [comment]
名札回収、再利用するとして、在庫を置いておく場所がほしいなーって思った。

私達って、物理的な資産って誰かが保管とかしてるんだっけ？

**Comment by IkezoeMakoto** [comment]
先日口頭で話した内容から

第一回である今回は参加料は取らない方向で、人が集まれば第二回以降は有料も検討。

それに伴い、名札はやるのであれば（少なくとも第一回は）運営枠で準備できる範囲で検討する。

**Comment by IkezoeMakoto** [comment]
ということでこちら検討しないとですね〜〜。

**Comment by IkezoeMakoto** [comment]
## 名札を用意するメリット
* 名前がわかるようになるので話しかけやすい
* （区別できるようにすれば）運営側か一般参加かわかるので相談しやすい

## 名札を用意するデメリット
* 金銭的コスト（シールタイプであれば500円くらい）
* 名前を書くコスト（予め印刷しておくか、当日書いてもらうか程度）
* 名札を買いに行く手間（↑のやつで買うのであれば、オンラインで買えるが事前に用意しておかないと間に合わないかも）

**Comment by klack710** [comment]
■今思ったこと
逆に、名札ないとどう困るか試す意味でも、むしろ名札なしをやってみたい。
一般的な名札なしイベントだと、名刺交換したりするじゃん？

自己紹介LTだけではどう不十分なのか？というのを知ってみたい気がする。
もしかすると、必要なのは名札ではなく、名刺交換タイムなのかもしれないとか。

**Comment by IkezoeMakoto** [comment]
まぁ正直なくてもそんなには困らないと思うよ。今回人数も少ないし。

ただ名札があると話すきっかけになったり、自己紹介がしやすいから導入できるならしてもいいよね。という話。

それと名刺を休日も持ち歩いてる人は少数だし、名刺は会社のしかない人もいるから嫌がる人もいる、ので個人的にはあまり気は乗らないかな。

**Comment by klack710** [comment]
あーなるほどなー
やるやらないどちらにしろ、アンケートほしいって思った_φ(･_･

1. やるやらない
2. やる場合の購入とか

これぞえさんにアサインしていいです？
アサインギリギリになって申し訳ない・・・

**Comment by IkezoeMakoto** [comment]
え、やるやらないの判断含めて、ということですか？
正直僕はあったほうがいいと思っててういろうさんがなくても良くね？派だと思ってるのでどっちかに判断を任せるという選択はないのかなと思っていたんですが

**Comment by klack710** [comment]
@IkezoeMakoto 
なるほど、でしたらやりましょう！

やるとして、そこの手配とかお願いしてもいいですか？

**Comment by IkezoeMakoto** [comment]
承知〜。では私の方で手配、準備しておきますね。

**Comment by klack710** [comment]
ありがとうございます！
ギリギリのアサイン申し訳ないです！

もし他にわからない情報あったらまた聞いてください！

**Comment by IkezoeMakoto** [comment]
発注しましたー。木曜日に届くはず。

**Comment by IkezoeMakoto** [comment]
ということで、一旦こちらはクローズ
お金どうするかは集まったときに議論しましょ。
