### ISSUE TITLE
当日の事前説明の準備

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#43]
事前説明の準備（会場案内、当日の流れを説明）

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487983558_

**Comment by IkezoeMakoto** [comment]
ここらへん特に希望なければ @klack710 にお願いしたいかなと思ってるけどどう？

**Comment by klack710** [comment]
はいはーい！
じゃあ私の方でいい感じにすすめておきますね。
もし手が足りなくなりそうになったら、また『手伝ってー！』って連絡します！

**Comment by IkezoeMakoto** [comment]
こちらは準備できたらクローズする感じでお願いします〜

**Comment by klack710** [comment]
はーい！
一応たたきを用意して、シェアするまではやってからクローズしようと思いますー

**Comment by klack710** [comment]
これ、WGもくもく会で作ります！！！

**Comment by masaki-obata** [comment]
@IkezoeMakoto 
> 事前説明の準備（会場案内、当日の流れを説明）

これって、ぞえさんの前日広報があるから、必要なものって、もしかしてない？
https://github.com/oystersjp/neta-note/issues/38

あるいは、当日のオープニングで会場案内や当日の流れ説明するって話？

**Comment by IkezoeMakoto** [comment]
>これって、ぞえさんの前日広報があるから、必要なものって、もしかしてない？
当日の事前説明なので、会の諸注意とかをイメージしてたので必要だと思ってます。

**Comment by klack710** [comment]
おっけー！ならオープニング・・クロージングのスライドで話せてたらOKってことね！

**Comment by IkezoeMakoto** [comment]
完
