### ISSUE TITLE
受付担当の決定

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#44]
受付担当の決定

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487984800_

**Comment by cocoeyes02** [comment]
受付何やるかあんまりわかっていませんが、僕当日まだ手すきっぽいので担当しましょうかー？

**Comment by cocoeyes02** [comment]
担当は僕で決定したら、この issue 自体は閉じるだろうけど
何をやるかみたいなの決める issue  は別途立てた方が良いですかね？

**Comment by IkezoeMakoto** [comment]
> 担当は僕で決定したら、この issue 自体は閉じるだろうけど
> 何をやるかみたいなの決める issue は別途立てた方が良いですかね？

そうしよう！

**Comment by cocoeyes02** [comment]
じゃあこの issue はクローズします！
