### ISSUE TITLE
会場案内担当の決定

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#45]
会場案内担当の決定

_Originally posted by @IkezoeMakoto in https://github.com/oystersjp/neta-note/issues/24#issuecomment-487985064_

**Comment by okashoi** [comment]
「会場案内」が指す役割は

* 到着者から連絡来たら 1F まで向かう
* 入り口を開けて無限 LT の参加者であることを確認
* 参加者の場合、会場まで案内

という認識でよいかな。

であれば WG 社員である必要がある。

**Comment by IkezoeMakoto** [comment]
その認識！

**Comment by IkezoeMakoto** [comment]
こちら消去法で @okashoi にお願いしたいと思うけど大丈夫ですか〜〜？

**Comment by IkezoeMakoto** [comment]
@okashoi ping

**Comment by okashoi** [comment]
引き受けます！

連絡先が @klack710 の twitter アカウントだったと思うので、そこの取り次ぎだけ段取り決めとかないとね

**Comment by masaki-obata** [comment]
1. #endless_lt タグはおかしょいでおってもらう
2.  私に連絡が来たら、すぐに連絡するよ。必要だったら、 @nyamucoroで検索もあり

**Comment by klack710** [comment]
1. #endless_lt タグはおかしょいでおってもらう
2. 私に連絡が来たら、すぐに連絡するよ。必要だったら @nyamucoroで検索もあり

**Comment by okashoi** [comment]
DM が来ることは...ないかな？

**Comment by okashoi** [comment]
まあ、連絡してくれるなら大丈夫か

**Comment by klack710** [comment]
わーお、しまったそうだねー
DMを個人チャンネルに自動通知考えたけど、一応一旦それはなしにしたいー
なので、DM来たらすぐ連絡するー

**Comment by okashoi** [comment]
んじゃあ決定で
