### ISSUE TITLE
司会進行担当決め

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/neta-note#46]
あと司会進行役が別途必要だと思う。

_Originally posted by @okashoi in https://github.com/oystersjp/neta-note/issues/24#issuecomment-488224498_

**Comment by IkezoeMakoto** [comment]
司会進行は今回主導してくれてる @klack710 が適任かな、と思うけどどうですかね？

あと司会進行担当には

#43 

もやってもらいたい

**Comment by okashoi** [comment]
個人的には @klack710 にやってほしい。

（無理なら私も引き受けられます）

**Comment by klack710** [comment]
司会進行も私やってみますねヽ(=´▽`=)ﾉ

**Comment by IkezoeMakoto** [comment]
お願いします！

わからないことや相談ごとあれば何でも聞いてください〜〜

**Comment by klack710** [comment]
たぶん、司会してるときにまだ到着してない人いたときの誘導とかを、他の運営スタッフにも手伝ってもらう形になりそう。

**Comment by IkezoeMakoto** [comment]
> たぶん、司会してるときにまだ到着してない人いたときの誘導とかを、他の運営スタッフにも手伝ってもらう形になりそう。

これは会場案内で担当別に分けてるので大丈夫そうです！

**Comment by IkezoeMakoto** [comment]
担当ぎめできたのでこのissueはクローズ
