### ISSUE TITLE
アンケートの内容を考える

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#47]
あ、アンケートの内容考えないといけないっすね

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/24#issuecomment-488225983_

**Comment by klack710** [comment]
たしかーに。

ちょっと運営の方でキツめなので、02にこのまま任せられると助かる。

**Comment by cocoeyes02** [comment]
承知でーす！
じゃあ、参加者に聞きたいこととか、、GW 中で適当に書いていただければよしなにしてアンケートの叩き作っておきますー

**Comment by IkezoeMakoto** [comment]
一旦メモ代わりに聞きたいこと

・会場について（設備等）
・運営について
・無限LTについて（会そのもの、人数は適切だったか）
・飲食物について
・有料化について

**Comment by IkezoeMakoto** [comment]
こちら進捗どうですか？

**Comment by cocoeyes02** [comment]
だいたいこんな感じ？（あとで Google フォームに書きます）

# 無限LTについて（会そのもの、人数は適切だったか）
## 無限 LT 全体について
* 満足度
* 何かあれば一言をお願いします

## 人数について
* 満足度
* 何かあれば一言をお願いします


# 会場について（設備等）
* 満足度
* 会場について何かご意見がありましたら、こちらにお願いします

# 運営について
* 満足度
* 運営について何かご意見がありましたら、こちらにお願いします


# 有料化について
* 飲食物の提供等のため、参加者から参加費（1000円ほど）を頂こうと思っていますがいかがですか？

**Comment by klack710** [comment]
アンケートだけど、クロージングにアンケートを書く時間を取りましょう。
なので、完成は無限LT会開催までにお願いしたい！

**Comment by klack710** [comment]
■発表のしやすさについて
発表者のレベル帯（レベルが高かったか？低かったか？）
発表の雰囲気（話しやすかったか？話しづらかったか？）

『レベル帯』がピンときてない。
たぶん聞きたいことの本質は、『発表しやすかったか』なので、
以下みたいに聞くと私は良いと思うけどどう？(アンケート作るの大変だけど)
・発表はしやすかったか
・発表しにくかった場合、その要因をチェックしてもらう
■発表のレベル差を感じたから
■無限LT会という特殊な環境で慣れない
■画像などの素材を事前準備しないとLT出来ない
■練習時間を事前に用意しないとLT出来ない
■その他

**Comment by klack710** [comment]
言い方の問題だけど
```
飲食物の提供等のため、参加者から参加費（1000円ほど）を頂こうと思っていますがいかがでしょうか（
```

```
参加費を1000円ほど頂くことで、飲食物の提供が出来ますがいかがでしょうか
1. 無料で持ち込みの形式がいい(今回)
2. 参加費徴収の方がいい
3. その他
```

**Comment by cocoeyes02** [comment]
> ・発表はしやすかったか
> ・発表しにくかった場合、その要因をチェックしてもらう
> ■発表のレベル差を感じたから
> ■無限LT会という特殊な環境で慣れない
> ■画像などの素材を事前準備しないとLT出来ない
> ■練習時間を事前に用意しないとLT出来ない
> ■その他

なるほど、であれば発表しやすかった、どちらとも言えない、しにくかった場合でラジオボタンを設定して、
どちらとも言えない、しにくかった場合は要因でチェックボックスを設定するようにしましょうかー

**Comment by cocoeyes02** [comment]
> 参加費を1000円ほど頂くことで、飲食物の提供が出来ますがいかがでしょうか
> 1. 無料で持ち込みの形式がいい(今回)
> 2. 参加費徴収の方がいい
> 3. その他

これはこんな感じの言い方のほうがいいですね！了解です！

**Comment by cocoeyes02** [comment]
じゃあ適当にフォーム作りますねー

**Comment by klack710** [comment]
発表人数→本質は発表頻度

**Comment by klack710** [comment]
発表何回したかったか（もっとたくさんLTしたかった？）

**Comment by cocoeyes02** [comment]
でけた
https://forms.gle/zXTDqaPb2fB7NFUU9

**Comment by klack710** [comment]
ここ、オープンなリポジトリだから、編集リンクはおすすめしないー

**Comment by cocoeyes02** [comment]
あと QR コードっす

![endless_lt_survey](https://user-images.githubusercontent.com/21007314/57577072-d9918b00-74a9-11e9-9d4c-ed59fb4c1785.png)

**Comment by IkezoeMakoto** [comment]
完
