### ISSUE TITLE
受付担当がやることを決める

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#48]
担当は僕で決定したら、この issue 自体は閉じるだろうけど
何をやるかみたいなの決める issue  は別途立てた方が良いですかね？

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/44#issuecomment-488228381_

**Comment by cocoeyes02** [comment]
とりあえず

* 名簿を用意して、きたかどうか確認
* （名札を用意するなら渡す https://github.com/oystersjp/neta-note/issues/40#issuecomment-487859807 ）

**Comment by cocoeyes02** [comment]
@okashoi さんと「名簿を用意して、きたかどうか確認するだけなら迎えにいく人がやればいいのでは？」みたいな話をした

**Comment by klack710** [comment]
@cocoeyes02 
■名札について
1. @IkezoeMakoto が購入＋現在管理しています
2. 会場で保管しているので、当日受け取ってください
3. 使い捨てのものなので、回収については考えなくて大丈夫です！

**Comment by cocoeyes02** [comment]
お！あざます！
じゃあ、当日受けつけやることは以下ですね！

・名簿を用意して、connpass ID から来場したか確認
・名札を渡す

**Comment by cocoeyes02** [comment]
名札の名前は自分で書いてもらう方式ですかね？

**Comment by IkezoeMakoto** [comment]
完
