### ISSUE TITLE
無限 LT 後の懇親会について

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#51]
一旦懇親会についてで issue 立てます！

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/24#issuecomment-489906856_

**Comment by cocoeyes02** [comment]
ロスタイム後に、懇親会参加する人挙手で聞いてから予約したった

https://s.tabelog.com/tokyo/A1303/A130301/13141751/

**Comment by cocoeyes02** [comment]
今後いきなり予約するのは厳しいので、参加者枠で懇親会参加枠みたいなの増やした方がいいかもしれない

**Comment by IkezoeMakoto** [comment]
懇親会も終わったので終了
