### ISSUE TITLE
振り返りの場所の確保

### ISSUE THREAD

**Issue by klack710** [oystersjp/neta-note#57]
2019/05/19にむげんの振り返りをしよう。その場所の確保

#34

**Comment by klack710** [comment]
@ShuzoN 

場所の確保をよろしく！
確保出来たら、完了に持っていってほしい！

もし難しそうなら、また別な場所を話し合おう！

**Comment by ShuzoN** [comment]
memo:

振り返りの場所と日時

日時: 5/19(日)
場所: VG(仮)

**Comment by ShuzoN** [comment]
会社で1番でかい部屋を取っておいた @しりうす

**Comment by okashoi** [comment]
せば close してないなこれ。とじる。
