### ISSUE TITLE
第 2 回 公開版無限 LT（第4回無限 LT 会）

### ISSUE THREAD

**Issue by okashoi** [oystersjp/neta-note#60]
* 前回
    * https://github.com/oystersjp/neta-note/issues/24
* KPT
   * https://scrapbox.io/oystersjp/%E7%84%A1%E9%99%90_LT_KPT
   * https://docs.google.com/spreadsheets/d/10k8XsVkilQj6MNbF_qGfnUbA0Ljk2trNkrJ87LLYFtU/edit#gid=1820285867

**Comment by klack710** [comment]
定期開催するなら、専用のリポジトリ立ててもいいよねって話もあった

**Comment by ShuzoN** [comment]
> 定期開催するなら、専用のリポジトリ立ててもいいよねって話もあった

一旦やらない

**Comment by ShuzoN** [comment]
うぉおおおおおおおお、俺が2回目のリーダーだああああああああああああああ

**Comment by ShuzoN** [comment]
2回目の議事rockはこれだっ

https://scrapbox.io/oystersjp/2019%2F5%2F29_%E7%AC%AC2%E5%9B%9E_%E7%84%A1%E9%99%90LT%E3%82%AD%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88_mtg

**Comment by ShuzoN** [comment]
scrapboxがmdではないせいでコピーすると謎の記号でる件について小一時間話したい。

[* 新しく決まったこと]

 リーダー: shuzon
 運営:  [cureseven] [akki] [zoe] [shuzon]
 [* テーマは「無限LTの中でLTを作らせること」] 参加者目線
 [* ターゲット: 「ネタはあるけどまだLTとして実装してない(上級者)/ LTしてみたいけどまだしたことがない(初心者)」人を集める]
 	[* もくもくの時間を作る]　新しい要素
  LT会における1発目のLTは [* 初心者に向けて「爆速でLTを作る方法」を最初のLTとして運営が発表する]
  2LOOPはしたい
  休憩10分
  1本目のLTは作ってきてもらう
  	これ以上作ってくるのは禁止
  	原則その場で作ったものを発表して欲しい
  ネタは自己紹介の最後に書いておく
  	ここから次のLTを決める
  	投票制? twitterのアンケートとかでいいと思う #endless_lt をつけてもらう
  自己紹介の最後に無限LT内で聞いてみたいネタを書いておく(request)
  	もくもくで作ってくれる人がいるかも？
  ネタもくもくタイム30分
  もくもくが過ぎたらLTがスタートする
  Oystersをそこそこの割合で混ぜておく
  焦燥感の中でLTを作って欲しい by shuzon

[* next action 決め]
 	当日の運営の大まかなタイムスケジュール
 	コンパスページの作成
 		このタスクが大きい
 		https://oysters.connpass.com/event/129365/
 		https://github.com/oystersjp/neta-note/issues/60

**Comment by cureseven** [comment]
test

**Comment by ShuzoN** [comment]
お疲れ様でした
