### ISSUE TITLE
無限LT オープニングLTつくる

### ISSUE THREAD

**Issue by ShuzoN** [oystersjp/neta-note#64]
ref: https://github.com/oystersjp/neta-note/issues/63

```
[* テーマは「無限LTの中でLTを作らせること」]
	[* もくもくの時間を作る]
	[* 初心者に向けて「爆速でLTを作る方法」を最初のLTとして運営が発表する]
		質とかいいから出せ
```

**Comment by BBCapMegane** [comment]
5分LT想定で作成

**Comment by ShuzoN** [comment]
6/7に一旦提出

**Comment by BBCapMegane** [comment]
前に作ったやつ
ベースとして使う

https://docs.google.com/presentation/d/1DQVRCD8e1GE2JKRI6phOym1WyUWW_vEz681_wlHyolE/edit?usp=sharing

**Comment by cureseven** [comment]
6/30完成

**Comment by cureseven** [comment]
オープニングLTで素早くLTを作るナレッジ共有して欲しいです

**Comment by BBCapMegane** [comment]
https://docs.google.com/presentation/d/1NKRb58QKdeP0848AOjlzeILhRr7MWabg1i5OE2FMvEk/edit?usp=sharing
一旦作りました！、できれば感想ほしい
(ナレッジがあんまなくてすんません)

**Comment by ShuzoN** [comment]
わろたwww O'Reillyならぬ O'ysters

![image](https://user-images.githubusercontent.com/5877377/58756105-7e910800-852c-11e9-9c9a-6a9ff81fcfb5.png)

**Comment by ShuzoN** [comment]
![image](https://user-images.githubusercontent.com/5877377/58756120-d0d22900-852c-11e9-9823-d91ab6b74cff.png)

**無限に** LTし続けます

ただし時間は有限。

でいいかも、次の2枚のスライド冗長に見える


![image](https://user-images.githubusercontent.com/5877377/58756117-b7c97800-852c-11e9-87f4-4b67691c447f.png)

テーマは **ありません** みたいに結構強調してもいいかも

![image](https://user-images.githubusercontent.com/5877377/58756125-f828f600-852c-11e9-9355-ac2cd2e57f4f.png)

"ノリ"はカタカナの方が読みやすいかも

![image](https://user-images.githubusercontent.com/5877377/58756132-0d058980-852d-11e9-91d4-01218cf08c32.png)


ぎっちり感があるので例は2~3こ個くらいでいいかな...?

![image](https://user-images.githubusercontent.com/5877377/58756140-2575a400-852d-11e9-916f-1168747d5c4d.png)

このスライドのメッセージすごく無限LTにおいては大事なので枚数と時間使ってもいいかも!

--

LT作成お疲れ様です...!
後半につれて画像少なくなって、文字がぎっちりするのが気になりました。
もうちょい画像入れて、空白があるとぱっと見でわかるかなーと思いました

が、内容的には◎👍
出だしのオライリーわらったのでとてもいいと思いました!

**Comment by ShuzoN** [comment]
@BBCapMegane

**Comment by IkezoeMakoto** [comment]
面白い！FBはしゅーぞーがだいたいしてくれてるので自分からは特にないです〜

**Comment by BBCapMegane** [comment]
お二人ともレビューありがとうございます！
指摘点を踏まえ修正しました！確認していただけると幸いです！
https://docs.google.com/presentation/d/1NKRb58QKdeP0848AOjlzeILhRr7MWabg1i5OE2FMvEk/edit?usp=sharing

**Comment by ShuzoN** [comment]
めっちゃいい感じ！@BBCapMegane
最後のスライドにOysterが運営やってるよ〜興味あれば入ってね、と書いておくとなお良いかも！

**Comment by cureseven** [comment]
@BBCapMegane 
スライド作成ありがとうございます！
私からも何点かFB

> 過去「アロハシャツのススメ」「個人開発に自動デプロイを導入した話」
> その他 hogehoge..
その他にたくさんあるので過去はもう書かなくて良さそう、その他をちなみに「第1回のLTの内容」こんな感じでしたって紹介に変えるのはどうでしょうか

> お土産　＋LT
新規で作ったLT？とか自分が作ったLTってニュアンス加えたいです

> アドリブと熱意でトーク伝えたいという気持ちが大事！
ここでいらすとやさんの絵消えないようにしたい
(別のスライドかと思って読み直しちゃった)

よろしくお願いします！

**Comment by BBCapMegane** [comment]
@cureseven 
レビューありがとうございます！
直してみたので、確認お願いします！

https://docs.google.com/presentation/d/1NKRb58QKdeP0848AOjlzeILhRr7MWabg1i5OE2FMvEk/edit?usp=sharing

> 最後のスライドにOysterが運営やってるよ〜興味あれば入ってね、と書いておくとなお良いかも！
↑に関しては、Oystersが運営してる旨は入れました、
入ってねの部分は、入れませんでした
Oystersの方針的には積極的にはメンバー募集はしてない感じですよね？(あれ違ったけ？)

**Comment by ShuzoN** [comment]
オープニングLTはdone
