### ISSUE TITLE
コンパスページの作成

### ISSUE THREAD

**Issue by ShuzoN** [oystersjp/neta-note#65]
ref: https://github.com/oystersjp/neta-note/issues/63

このタスクが大きい
 https://oysters.connpass.com/event/129365/
 https://github.com/oystersjp/neta-note/issues/60

公開無限LT #2 のコンパス draft
https://connpass.com/event/133501/edit/

**Comment by ShuzoN** [comment]
以下のディレクトリで管理していこうね

```
oysters/neta-note/endless_lt_2/connpass
```

**Comment by cureseven** [comment]
二週間後に公開

**Comment by ShuzoN** [comment]
6/14な

**Comment by cureseven** [comment]
参考
https://scrapbox.io/oystersjp/2019%2F5%2F29_%E7%AC%AC2%E5%9B%9E_%E7%84%A1%E9%99%90LT%E3%82%AD%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88_mtg

**Comment by cureseven** [comment]
https://github.com/oystersjp/neta-note/pull/73
