### ISSUE TITLE
当日までの運営の大まかなタイムスケジュールつくる

### ISSUE THREAD

**Issue by ShuzoN** [oystersjp/neta-note#66]
ref: https://github.com/oystersjp/neta-note/issues/63
ref: https://github.com/oystersjp/neta-note/issues/65
ref: https://github.com/oystersjp/neta-note/issues/60

**Comment by cureseven** [comment]
6/7定例MTGまで

**Comment by ShuzoN** [comment]
6/7 無限LTオープニングLT作成締め切り

6/10 どういう人に来て欲しいか決めよう
   - 新規何人とかそういう話
   - 具体的な方針極め
     - 差し入れ面白かったで賞
     - ベストスピーカー賞
   など仕掛けがあるとよりLT大会として面白くなるかも

6/14 connpassページ公開

おおまかなこと
```
  - 対象の人決めた
  - LTの対象話題決める(これは今まででいいかも)
    - 前回の風景を載せる
    - 1日のスケジュール決める(これは振り返りで提案されているので参考にする)
  - ざっくりの流れを決める
    - 前回とだいたい一緒でok 
    - ガチャする1line codeでも書けばok?
  - 参加者への諸注意
    - 飲食物はありにする？懇親会でピザ出すならvgスポンサー使えば良さそう
       - #sponsor チャンネル in vg
  - 接続端子のチェック
  - 持ち物
    - 前回と同じでいいかも
    - 差し入れ面白かったで賞作ると楽しいかもね
  - 会場への入場
    - ここは @ShuzoN が調べる
```
6/14 - 6/16 本格的な広報開始
  - oystersには全員頼る
  - なんならサポーターズにRTしてもらってもいいかもね
    - ここで「どういう人に来て欲しいか」が効いてくる
6/21 
  - 受付担当の決定 
  - 受付配布物の決定
    - 名札とか
  - 司会進行の担当決め 
  - オープニングスライドがこの時点のイベント構想とあっているかチェック
  - 名札やお金の話
 
6/28
  - 入退館フローのチェック
  - タバコ問題(これかなりめんどい)
  - 懇親会の話をつめる
  - 会場設営の話

**Comment by ShuzoN** [comment]
大枠決まってるのでdone
