### ISSUE TITLE
当日の運営の動きを確認する

### ISSUE THREAD

**Issue by cureseven** [oystersjp/neta-note#75]

**Comment by cureseven** [comment]
準備
[] オフィス解錠（WG 社員）
[] 簡単に掃除（目立つゴミを捨てるなど）
[] 机・椅子を参加人数に応じて配置
[] wifi 情報のやつを机の上に置いておく
[] 延長コード手配
[] プロジェクタ・スクリーン設置
[] 演台をスクリーン横に持ってくる
[] 照明の調整
[] マイクの設定
[] （できたら）観葉植物を使って執務室との区切りを意識させる
[] ゴミ袋の設置
片付け
[] 最後の参加者がビルから退出したことを確認
[] 忘れ物の確認（Oysters メンバーの誰かが預かる？）
[] 掃除
[] 机拭き
[] ゴミ捨て
[] 原状復帰（WG 社員主導）
[] プロジェクタ・スクリーン
[] 机・椅子
[] wifi 情報のやつ
[] 演台
[] 延長コード
[] マイク
[] 観葉植物
[] 施錠

**Comment by cureseven** [comment]
事前に準備するモノ
 看板で表示する用の印刷物
 名札ケース
 紙とペン
 食べ物・飲み物（途中で届く場合、その手はずを確認）
 皿・コップ
 ウェットティッシュ
 wifi 情報のやつ（各会議室から）
 connpass 参加者一覧表（紙に印刷）
 椅子が足りなさそうなら別途会議室を押さえておいて、椅子を持って来られるようにしておく
 カメラ（広報のものを借りる）

**Comment by cureseven** [comment]
会場設営
 簡単に掃除（目立つゴミを捨てるなど）
 机・椅子を参加人数に応じて配置
 食べ物
 飲み物
 皿
 コップ
 ウェットティッシュ
 wifi 情報のやつ
 受付の設営
 机
 椅子
 名札ケース
 紙とペン
 connpass 参加者一覧表
 オフィス受付から Room 0 につながる扉を開放しておく
 オフィス受付周辺に看板を設置
エントランスの範囲に入るように
エレベータホールは共用部扱いなので NG
 会議室方面の扉に利用できない旨の張り紙をする
 プロジェクタ・スクリーン設置
 いい感じのスライドを映しておく（wifi 情報など）
 発表者に事前の接続確認を依頼（司会進行）
 演台をスクリーン横に持ってくる
 照明の調整（Room 0 の黒板寄りの証明は スイッチ B が対応している）
 マイクの設定
 音楽を流す
 ゴミ袋の設置（燃えるゴミ／燃えないゴミ／缶・ペットボトル）
 （できたら）観葉植物を使って執務室との区切りを意識させる

**Comment by ShuzoN** [comment]
https://github.com/oystersjp/neta-note/issues/70

**Comment by cureseven** [comment]
最後の参加者がビルから退出したことを確認
 忘れ物の確認
 ある場合はハッシュタグなどで周知
 原状復帰・物品返却
 プロジェクタ
 スクリーン
 机
 椅子
 wifi 情報のやつ
 演台
 延長コード
 マイク
 カメラ
 観葉植物
 看板
 名札ケース
 紙とペン（紙は破棄？）
 会議室方面の通路封鎖の張り紙
 掃除
 机拭き
 ゴミ捨て
 あまった食べ物・飲み物の処分
近く開催されるイベントがあれば、使ってもらう（賞味期限・保存方法に気を遣う）
少量であればその場で処分
翌日以降、全社告知して処分してもらう（賞味期限・保存方法に気を遣う）

**Comment by cureseven** [comment]
# 役割きめ
音楽流す人

司会進行（スライド作成込）

タイムキーパー

受付

会場設営の陣頭指揮

片付け
全員
SNS 実況

カメラ

20:00 以降到着／離脱の人の案内

**Comment by ShuzoN** [comment]
あと、当日に用意したお酒とドリンク

**Comment by yutanpo1121** [comment]
てすと
