### ISSUE TITLE
キックオフやる

### ISSUE THREAD

**Issue by okashoi** [oystersjp/neta-note#80]
## キックオフのゴール

- [x] 無限 LT 会開催の動機の共有
- [x] 運営の方針すり合わせ
- [x] スケジュール（マイルストーン）のすり合わせ
- [ ] 役割分担

議事録は scrapbox で取る予定

**Comment by okashoi** [comment]
@cocoeyes02 @klack710 （CC: @yutanpo1121, ずんださん？）

雑にキックオフの予定を調整します〜

https://chouseisan.com/s?h=d64556f8c40a491e866628081f5e56b0

**Comment by okashoi** [comment]
キックオフやる前に本当に私がリーダーやるのかすり合わせないとな

> メモ：岡田も忙しくなってきたので、場合によっては延期 & ういろうさんにリーダーわたす

**Comment by cocoeyes02** [comment]
ういろうさん（@klack710 ）いなかったので、役割分担は別日開催

**Comment by okashoi** [comment]
議事録

https://scrapbox.io/oystersjp/2019%2F07%2F28_%E7%AC%AC3%E5%9B%9E_%E7%84%A1%E9%99%90_LT_%E4%BC%9A_%E3%82%AD%E3%83%83%E3%82%AF%E3%82%AA%E3%83%95
