### ISSUE TITLE
忘年会的なやつ

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#82]
今年は新規がかなり増えたので、忘年会的なやつやりたいっす！

ただ、12月とか忘年会シーズンで予定いっぱいだったり地元に帰る人もいるので、11月にやりたい気持ち

**Comment by cocoeyes02** [comment]
気が早いかもだけど多くの人に参加して欲しいので、9月末までには日付・場所・参加人数決めたいキムチ

**Comment by BBCapMegane** [comment]
先生LTはやりますか！？

**Comment by cocoeyes02** [comment]
この :ltjunkie: め！
せっかくならどっか借りて、飲み + LT 会やりますか！？

**Comment by okashoi** [comment]
内輪用の無限 LT 形式でいい感じがしてきた

**Comment by okashoi** [comment]
いや、全員がそれ望んでるわけではないよなあ

**Comment by cocoeyes02** [comment]
> 全員がそれ望んでるわけではないよなあ
それですよ
単純に飲みたいだけの人もいるはずなので、普通のLT会形式にしましょ

ただし、飛び入り参加は無制限で…あとはわかりますね？

**Comment by cocoeyes02** [comment]
居酒屋でやるのとどこか借りる（VGとかWGとか）のどっちが良いかな

**Comment by ShuzoN** [comment]
bbq

http://beergarden.jinnanken.com/

**Comment by BBCapMegane** [comment]
bbq いいね、神南軒行きたい

bbq ならこれとかもいいよ
https://park.realbbq.jp/

**Comment by cocoeyes02** [comment]
青空LTだ！（LTジャンキー的発想）

**Comment by cocoeyes02** [comment]
そしたらもはや忘年会じゃなくても良いかもですね
BBQオフ会！

**Comment by IkezoeMakoto** [comment]
日程調整中
締め切りは11/8(金)

https://chouseisan.com/s?h=58e97bb212784c9284b61dd99ca9a619
