### ISSUE TITLE
役割分担

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#85]
ういろうさん（@klack710 ）いなかったので、役割分担は別日開催

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/80#issuecomment-515736605_

**Comment by okashoi** [comment]
おおむね以下の内訳になる想定

* 全体統括（責任を取る人）
    * 進捗管理
    * 意思決定
    * リスクマネジメント
    * なんかあったら謝る
* 企画（全体の像を決める人）
    * 当日のタイムスケジュール
    * 懇親会企画
* 制作（細かいところを作り込む人）
    * connpass ページ
    * アイキャッチ画像（変えるなら）
    * リマインドメール送信
    * アンケート作成
    * T シャツ（つくるなら）
* 設営（必要なものを揃える人）
    * 会場との調整
    * 飲食物の手配
    * 物品購入
* 会計（お金を管理する人）
    * 運営にかかった全部のお金を把握する
    * 当日の募金の受取先
    * 収支の内訳をまとめる
    * 損益の取り扱い（損は割り勘、益は打ち上げに）

**Comment by okashoi** [comment]
きまった

https://scrapbox.io/oystersjp/2019%2F08%2F03_%E7%AC%AC3%E5%9B%9E_%E7%84%A1%E9%99%90_LT_%E4%BC%9A_%E5%BD%B9%E5%89%B2%E3%81%8E%E3%82%81_MTG
