### ISSUE TITLE
BBQオフ会

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#88]
そしたらもはや忘年会じゃなくても良いかもですね
BBQオフ会！

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/82#issuecomment-517202033_

**Comment by cocoeyes02** [comment]
とはいえ8月実施するにしては皆忙しい上でクソ暑そうなので、まあまあ涼しくなってきたぐらいにしましょうか！（9月末~10月ぐらい？）

**Comment by IkezoeMakoto** [comment]
もうクローズする？？
リスケして再度計画する？

**Comment by ShuzoN** [comment]
かなり寒くなってきたのでcloseで
