### ISSUE TITLE
懇親会の手配

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/neta-note#93]
関連して懇親会の手配

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/neta-note/issues/90#issuecomment-517912535_

**Comment by okashoi** [comment]
飲み物→カクヤスで注文
食べ物→？？

**Comment by okashoi** [comment]
食べ物

おにぎり
ピクニックセット

**Comment by okashoi** [comment]
サンドイッチ的なやつとか
